### ISSUE TITLE
UCP: Refactor the class components to function components

### ISSUE THREAD

**Issue by baurine** [pingcap-incubator/tidb-dashboard#105]
## Description

In the frontend react code, we mix the class component and function component together, so this task is to refactor the class components to function components.

100 points for each:

- [x] `packages/dashboard_components/*`
- [x] `packages/keyvis/`
- [x] `src/apps/dashboardSettings/`
- [x] `src/apps/userProfile/`
- [x] `src/components/*`
- [x] `src/layout/signin`

## Score 

* 100

## Mentor(s)

* @baurine  

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* React

**Comment by breeswish** [comment]
@Trade-Offf Hi, please try to pick up again. We have splited tasks into multiple pieces.

**Comment by baurine** [comment]
close this issue by PR #469
