### ISSUE TITLE
UCP: Refactor the `gorm.DB.Raw()` code

### ISSUE THREAD

**Issue by baurine** [pingcap-incubator/tidb-dashboard#108]
## Description

This task is to eliminate the `gorm.DB.Raw()` code in `pkg/apiserver/diagnose/query.go` to make it more elegant.

Example: see this [commit](https://github.com/pingcap-incubator/tidb-dashboard/pull/34/commits/175c39a5f36b11388896a3acc09e53d2ffca0ea9)

For example, a function is implemented by gorm.DB.Raw():

```go
func QueryTimeRanges(db *gorm.DB) ([]*TimeRange, error) {
	sql := `select
	distinct summary_begin_time,summary_end_time
	from cluster_events_statements_summary_by_digest_history
	order by summary_begin_time desc`
	timeRanges := []*TimeRange{}

	db.Exec(selectPerformanceDB)
	rows, err := db.Raw(sql).Rows()
	if err != nil {
		return timeRanges, err
	}
	defer rows.Close()

	for rows.Next() {
		timeRange := new(TimeRange)
		err = rows.Scan(&timeRange.BeginTime, &timeRange.EndTime)
		if err != nil {
			return timeRanges, err
		}
		timeRanges = append(timeRanges, timeRange)
	}
	return timeRanges, nil
}
```

It can be simplified and get more elegant by the following code:

```go
func QueryTimeRanges(db *gorm.DB) (result []*TimeRange, err error) {
	err = db.
		Select(`
			DISTINCT
			summary_begin_time AS begin_time,
			summary_end_time AS end_time
		`).
		Table("PERFORMANCE_SCHEMA.cluster_events_statements_summary_by_digest_history").
		Order("summary_begin_time DESC").
		Find(&result).Error
	return result, err
}
```

## Score 

* 300

## Mentor(s)

* @crazycs520 
* @baurine 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Go

**Comment by zzh-wisdom** [comment]
I have a question about function `genSumarySQLs`. I run this function separately, and the printed result is as follows.
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/52516344/75944318-5165f180-5ed2-11ea-9a42-bfb6ee3b8f20.png">
The usage of `join ` is very strange, I guess it means to get all the information from all the tables.
Maybe `join` should be replaced by `,`

**Comment by zzh-wisdom** [comment]
@baurine

**Comment by baurine** [comment]
hi @zzh-wisdom , as my understanding, `select * from t1, t2` is the same as `select * from t1 join t2`.

**Comment by zzh-wisdom** [comment]
I get it. Thanks

**Comment by zzh-wisdom** [comment]
@baurine ,what about this!
<img width="340" alt="image" src="https://user-images.githubusercontent.com/52516344/75945417-2761fe80-5ed5-11ea-8ab0-cfa0c5800c6d.png">
I think it is useless.

**Comment by baurine** [comment]
@crazycs520 please help to explain the usage of these lines code:

```
	for i := range subRows {
		row := subRows[i]
		row[1] = strings.Join(row[1:2], ",")
		newRow := row[:2]
		newRow = append(newRow, row[2:]...)
		subRows[i] = newRow
	}
```
and it seems the same logic duplicates in some methods, maybe we can extract it.

**Comment by breeswish** [comment]
Close since this task is proven to be not very useful.
