### ISSUE TITLE
UCP: Extract statement frontend as a npm package

### ISSUE THREAD

**Issue by baurine** [pingcap-incubator/tidb-dashboard#109]
## Description

This task is to extract the statement fronted as an individual npm package, so other projects can reuse it.

## Score 

* 605

## Mentor(s)

* @baurine  

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* React

**Comment by breeswish** [comment]
Closed since this task has been merged into https://github.com/pingcap-incubator/tidb-dashboard/issues/110 .
