### ISSUE TITLE
UCP: Add form validation for `log searching` page

### ISSUE THREAD

**Issue by Deardrops** [pingcap-incubator/tidb-dashboard#112]
## Description

Add form validation for `log searching` page. In search form, we should do some validation before send request to back-end. e.g. at least 1 component should be selected. When download logs, at least 1 finished task should be selected.

## Score 

* 50

## Mentor(s)

* @Deardrops 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Web programming, includes
	* Typescript
	* React (React Hook)

**Comment by breeswish** [comment]
Will be resolved by ourselves.
