### ISSUE TITLE
UCP: Popup error prompt when request failed for `log searching` page 

### ISSUE THREAD

**Issue by Deardrops** [pingcap-incubator/tidb-dashboard#113]
## Description

Popup error prompt when request failed for `log searching` page.

## Score 

* 50

## Mentor(s)

* @Deardrops 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Web programming, includes
	* Typescript
	* React (React Hook)

**Comment by SSebo** [comment]
@you06 Is tikv and dashboard can pick only one challenge at same time?

**Comment by SSebo** [comment]
@Deardrops mentor, PTAL

**Comment by Deardrops** [comment]
> @you06 Is tikv and dashboard can pick only one challenge at same time?

@SSebo yes, You'd only have one picked Issue, not matter in which repo.

**Comment by you06** [comment]
@SSebo No you can't pick up 2 issues from different repos. But you can work on both, and pick up before submit a PR, where there is a PR waiting for reviewed, you're allowed to pick up a new one.

**Comment by SSebo** [comment]
@you06 @Deardrops thanks for your explanation.
