### ISSUE TITLE
UCP: Improve node selector in `log searching` page

### ISSUE THREAD

**Issue by Deardrops** [pingcap-incubator/tidb-dashboard#114]
## Description

For improving readability, Node selector should show how many TiDB/TiKV/PD components are selected like:

![image](https://user-images.githubusercontent.com/1916485/76524753-988d4d00-64a5-11ea-91e3-047245311563.png)

Node selector should also be a standalone component to be reused.

## Score 

* 300

## Mentor(s)

* @Deardrops 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Web programming, includes
	* Typescript
	* React (React Hook)

**Comment by breeswish** [comment]
Will implement by our own.
