### ISSUE TITLE
UCP: Show component address in `log searching` detail page

### ISSUE THREAD

**Issue by Deardrops** [pingcap-incubator/tidb-dashboard#116]
## Description

For improving readability, we should show component address in logs previewing table.

## Score 

* 50

## Mentor(s)

* @Deardrops 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Web programming, includes
	* Typescript
	* React (React Hook)

**Comment by breeswish** [comment]
This issue is already implemented.
