### ISSUE TITLE
UCP: Show cached log file size in `log searching` page

### ISSUE THREAD

**Issue by Deardrops** [pingcap-incubator/tidb-dashboard#117]
## Description

Show cached log file size in logs searching progress:

![image](https://user-images.githubusercontent.com/9463871/75641299-c1763c80-5c72-11ea-9644-bd38cb46e3f0.png)

## Score 

* 605

## Mentor(s)

* @Deardrops 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang
* Web programming, includes
	* Typescript
	* React (React Hook)

**Comment by STRRL** [comment]
I found that there is a compression before downloading.

Should I use compressed file size or just origin text size.

If I need use the compressed file size, is there any elegant way to calculate the estimate size without executing real compress?

**Comment by Deardrops** [comment]
> I found that there is a compression before downloading.
> 
> Should I use compressed file size or just origin text size.
> 
> If I need use the compressed file size, is there any elegant way to calculate the estimate size without executing real compress?

@STRRL use the compressed file size.
For every request to task groups, You can use `os.Stat(task.saveLogPath)` to get the current log file size.

**Comment by STRRL** [comment]
Hi @Deardrops , here are 3 position that could display log file size.

![](https://i.imgur.com/EllEd5Y.png)

It is expected that show file-size in all these position? Or just apart of these.

**Comment by Deardrops** [comment]
@STRRL all places
