### ISSUE TITLE
UCP: Remove go vendor folder

### ISSUE THREAD

**Issue by Deardrops** [pingcap-incubator/tidb-dashboard#119]
## Description

Remove go vendor in:
https://github.com/pingcap-incubator/tidb-dashboard/blob/35a6e979dca927d7169422fd0f8697dfb4f592e8/scripts/generate_swagger_spec.sh#L23-L25

## Score 

* 50

## Mentor(s)

* @Deardrops 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang

**Comment by you06** [comment]
@zzh-wisdom try again please.

**Comment by zzh-wisdom** [comment]
When simply removing `vendor`, I get an error when running command `make dev`. When Changing the script to `swag init --parseDependency -g cmd/tidb-dashboard/main.go` and running, there is also an error.

**Comment by breeswish** [comment]
@zzh-wisdom You can duplicate the structure of diagnosepb in the source code. In this way there is no need for swag to parse vendor.

**Comment by breeswish** [comment]
Implemented by #275
