### ISSUE TITLE
UPC: Add probe IP support for TiDB,PD,TiKV

### ISSUE THREAD

**Issue by Deardrops** [pingcap-incubator/tidb-dashboard#121]
## Description

Add probe IP support for TiDB,PD,TiKV.

When set `--host=0.0.0.0` for TiDB, TiDB Dashboard cannot get the real IP, we should let TiDB probe and report its real IP.

## Score 

* 605

## Mentor(s)

* @Deardrops 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang
* Rust

**Comment by STRRL** [comment]
Here is a complex problem that I can not find out which IP is "real IP" with many network interfaces.

Or just report every IP?

**Comment by Deardrops** [comment]
> 
> Here is a complex problem that I can not find out which IP is "real IP" with many network interfaces.
> 
> Or just report every IP?

@STRRL We deal with the simple case only:
Only one network interface and a unique `real IP`.

The complex problem you mentioned could not be handled.

**Comment by STRRL** [comment]
I have a bad experience about this problem. It occurs in the self-written operating/monitoring system for my company.

This system pick up the first IPv4 address that not owned by `loopback` as node's IP.  It rarely bring the expected result. In the end, we take all IPs.

I think it might meet same problem.

**Comment by Deardrops** [comment]
@STRRL How about this way? https://stackoverflow.com/a/23558495
if an unexpected IP address returned, we could use the origin `0.0.0.0`.

**Comment by STRRL** [comment]
> How about this way? https://stackoverflow.com/a/23558495

I know how to fetch all IP of my machine. In fact, IPs from this way are sorted in a stable order.

> if an unexpected IP address returned, we could use the origin 0.0.0.0.

The problem is to found out the EXPECTED IP from IPs.

I suggest use all IP, do not contains any "pick one" logic.

**Comment by Deardrops** [comment]
@STRRL The demand of probe IP are:
1. Try to provide only 1 external IP if `--host=0.0.0.0`.

Because TiDB Dashboard need know the IP of every components (TiDB, TiKV, PD), display IP + port as its name in UI, also, Dashboard back-end server uses the IP to send request to specific components. We do not use all IPs here because both in UI and backend-server, 1 IP indicates 1 component is enough.

2. Otherwise, use the `--host=0.0.0.0` parameter as probe IP.
If these are multiple network interface, pick the expected one from them is not an easy task. So for simplify this task, we do not deal with this case.

**Comment by STRRL** [comment]
@Deardrops Can not help me to check the logic?

1. if `--host` is not setted by `0.0.0.0`, report this parameter
1. if there is ONLY ONE valid IPv4 address( no loopback ), report this IP.
1. elsewise fallback to `0.0.0.0`

**Comment by Deardrops** [comment]
@STRRL Right. But one more thing, TiDB has a parameter [`--advertise-address`](https://pingcap.com/docs-cn/dev/reference/configuration/tidb-server/configuration/) to indicates its external IP, so the logic should be:

1. if `--advertise-address` is not empty, report this `advertise-address`.
2. if `--host` is set to `0.0.0.0`, but `--advertise-address` is empty, there is ONLY ONE valid IPv4 address(no loopback), report this IP.
3. elsewise fallback to `0.0.0.0`

**Comment by STRRL** [comment]
@Deardrops Thanks! I will pick up this issue after earning enough score. LOL

**Comment by breeswish** [comment]
We now have ways to assign IP directly in our deployment tools. I'm going to close this issue.
