### ISSUE TITLE
UCP: Upgrade ant design to 4.0

### ISSUE THREAD

**Issue by baurine** [pingcap-incubator/tidb-dashboard#122]
## Description

This task is to upgrade the ant design to the recently released 4.0 version.

Ref: [migrate from 3.x to 4.0](https://ant.design/docs/react/migration-v4-cn)

## Score 

* 605

## Mentor(s)

* @baurine  

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* React

**Comment by SSebo** [comment]
@baurine  mentor, PTAL
https://github.com/pingcap-incubator/tidb-dashboard/pull/271
