### ISSUE TITLE
UCP: Support to show markdown content in the cluster diagnosis report

### ISSUE THREAD

**Issue by baurine** [pingcap-incubator/tidb-dashboard#123]
## Description

This task is to support to show markdown format content in the cluster diagnosis report.

In the diagnosis report page, there are some content's original format is markdown, they will be displayed as normal string, like the following example:

![d-m](https://user-images.githubusercontent.com/1284531/75855604-9dab2600-5e2d-11ea-88a8-2f0d7bbefa6a.png)

We need to support display the markdown format content.

### How to access this page

1. Run the local cluster with monitor by tiup: `tiup playground nightly --monitor`
1. Start the backend and frontend according to the instructions in CONTRIBUTING.md
1. Enter the "Cluster Diagnose" page, select the range start time, range duration, then clicking the "Start" button, it starts to diagnose

    ![image](https://user-images.githubusercontent.com/1284531/81392202-e2ff1300-9150-11ea-9d7e-529b933e1301.png)

1. After finishing the diagnosis, you can click the "View Full Report" to get the above detail report

   ![image](https://user-images.githubusercontent.com/1284531/81392385-2a859f00-9151-11ea-8aa7-8c3289872334.png)

You can mock some markdown content if there is no markdown format content currently.

## Score 

* 300

## Mentor(s)

* @baurine  

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* React

**Comment by Fullstop000** [comment]
@you06 this is an easy issue...

**Comment by you06** [comment]
@Fullstop000 sorry for missing the notification, the pick up should work now.

**Comment by baurine** [comment]
close by PR #466
