### ISSUE TITLE
UCP: Show progress when switching frontend page

### ISSUE THREAD

**Issue by baurine** [pingcap-incubator/tidb-dashboard#126]
## Description

This task is to show progress by the progress bar when switch frontend pages.

## Score 

* 301

## Mentor(s)

* @baurine  

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* React

**Comment by SSebo** [comment]
@baurine  Hi, mentor, is [`react-top-loading-bar`](https://klendi.github.io/react-top-loading-bar/) ok for this ?

**Comment by breeswish** [comment]
Looks like a good idea
