### ISSUE TITLE
Node count in cluster info table is wrong

### ISSUE THREAD

**Issue by zyguan** [pingcap-incubator/tidb-dashboard#130]
https://github.com/pingcap-incubator/tidb-dashboard/blob/35a6e979dca927d7169422fd0f8697dfb4f592e8/ui/src/apps/clusterInfo/components/ClusterInfoTable.js#L67

It seems not work?

![2020-03-02_172056](https://user-images.githubusercontent.com/6850317/75662767-9e677f00-5caa-11ea-9f15-3a70c0a771ea.png)

**Comment by mapleFU** [comment]
This pr is fixed by https://github.com/pingcap-incubator/tidb-dashboard/pull/133
