### ISSUE TITLE
UCP: Support TiDB retry

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#131]
## Description

Now we have a skeleton `tidb.Forwarder`, which connects directly to the first TiDB entry. However the first TiDB entry can be broken and we need to retry other TiDB nodes in the TiDB list.

The methods can be as follows:

1. Implement real health check and forwarding in forwarder. 

  - The forwarder need to support forwarding both MySQL TCP connection (which normally uses port 4000) and TiDB Status HTTP connection (which normally uses port 10080). You can retrieve both ports from tidb info entry.

  - The forwarder listens two port for forwarding MySQL TCP connection and TiDB Status HTTP connection in separate. The two ports are allocated dynamically depends on current available ports in the host and should be restricted to loopback interface (127.0.0.1) only.

  - The forwarder should check the health for each TiDB node (both 4000 and 10080) in background periodically, as well as switch to try other connection on demand when connect failed.

2. Change Dashboard's TiDB MySQL connection to connect to the forwarder's port.

3. Change Dashboard's TiDB Status connection to connect to the forwarder's port.

## Score 

* 1680

## Mentor(s)

* @breeswish 
* @HunDunDM 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Go TCP Programming

**Comment by Fullstop000** [comment]
@you06 How many scores do we (.* team) have in this project actually 😅

**Comment by you06** [comment]
@Fullstop000 I find #301 only which awarded your team 100 points, did I miss any PRs?

**Comment by Fullstop000** [comment]
@you06 just to make sure sre-bot is right 🤣.

**Comment by Fullstop000** [comment]
@you06 https://github.com/pingcap-incubator/tidb-dashboard/pull/304 has been merged.

**Comment by you06** [comment]
@Fullstop000 Fixed.

**Comment by you06** [comment]
> 
> 
> This pick has been automatically canceled after more than a week.

Caused by some mistakes, I think this will not take effect to the score, ignore it.
