### ISSUE TITLE
UCP: Use pflag instead of flag

### ISSUE THREAD

**Issue by HunDunDM** [pingcap-incubator/tidb-dashboard#138]
## Description

In the help information, we need to hide some debugging options. The `flag` package cannot fulfill this requirement. Replace it with the [`pflag`](https://github.com/spf13/pflag) package and hide the debugging options.

## Score

* 50

## Mentor(s)

* @hundundm

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang

**Comment by you06** [comment]
@zzh-wisdom problem solved, try again please.
