### ISSUE TITLE
UCP: KeyViz: Persist statistics

### ISSUE THREAD

**Issue by HunDunDM** [pingcap-incubator/tidb-dashboard#140]
## Description

Currently, all statistics collected by Key Visualizer are stored in memory. Once the program restarts, all previously collected statistics will be lost. We need persistent statistics, by writing this data to the DB and reading it on the restart.

## Score

* 1294

## Mentor(s)

* @hundundm

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang

**Comment by SSebo** [comment]
@HunDunDM hi, mentor, could explain a little bit of the difficult part of this issue? 4007 points is really high points.

**Comment by HunDunDM** [comment]
This issue originally needed to implement two features:
* Memory data persistence
* Timely store and access historical reports. Contains front-end and back-end
The second feature is canceled in this issue now. Currently only used to achieve memory data persistence, so the score is adjusted.
