### ISSUE TITLE
UCP: Support debug html templates without rebuild 

### ISSUE THREAD

**Issue by baurine** [pingcap-incubator/tidb-dashboard#150]
## Description

The diagnosis report is rendered by the backend go template.

At first, we put the templates in the individual html files like `diagnosis/index.html`, it easy to debug, when we modify the html file, it just needs to refresh the browsers instead of rebuilding the whole go code, but this solution prevents us to release the project as an independent binary. (note: you need to set the gin in debug mode by commenting the code `gin.SetMode(gin.ReleaseMode)` in the `pkg/apiserver/apiserver.go`).

Then we move the templates' contents into go code as strings, you can see the code in `pkg/apiserver/diagnose/templates.go`, it helps us to release the package but not easy to debug the templates, every time we modify the template's contents, we need to rebuild and re-run the go code.

So please help us to resolve this problem, debug the template without rebuild go code, and still can release the repo as an independent binary.

Ref: https://tech.townsourced.com/post/embedding-static-files-in-go/

The diagnosis report page:

![d-0](https://user-images.githubusercontent.com/1284531/75842253-cf5ec580-5e0a-11ea-915d-4b336586be83.png)

## Score

* 200

## Mentor(s)

* @breeswish 
* @baurine 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Go

**Comment by STRRL** [comment]
Here is what I do:

- move html content into new .html file: `index.html`, `table.html`
- create a customized `PreferLocalFileHTMLProduction` to replace `HTMLProduction`, It will reload content from local file if exists
- use `go-bindata-assetfs` generate resource .go file for production usage.
- use build tag to split debug and prod env (WIP)

My question is: Should I add the resource file generated by `go-bindata-assetfs`  into git repo?

If I do not do this, new developer need manually execute `go-bindata-assetfs` before start their work. It may cause some confuse.

**Comment by baurine** [comment]
hey @STRRL , I think you can make generate go file more automatical by adding the  extra step to Makefile

**Comment by STRRL** [comment]
OK, I will do this.

**Comment by breeswish** [comment]
Closed by #171
