### ISSUE TITLE
clusterinfo: Delete correspond TiDB node when tidb-ansible's content changed

### ISSUE THREAD

**Issue by mapleFU** [pingcap-incubator/tidb-dashboard#161]
## Feature Request

**Is your feature request related to a problem? Please describe:**

 Delete correspond TiDB node when tidb-ansible's tidb node list changed(removed).

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by breeswish** [comment]
Resolved by https://github.com/pingcap-incubator/tiup-cluster/pull/295
