### ISSUE TITLE
support TLS when mutual TLS authentication among TiDB components is enabled

### ISSUE THREAD

**Issue by LinuxGit** [pingcap-incubator/tidb-dashboard#174]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

If [mutual TLS authentication among TiDB components](https://github.com/pingcap/docs/blob/7a62321b3ce9318cbda8697503c920b2a01aeb3d/how-to/secure/enable-tls-between-components.md#enable-mutual-tls-authentication-among-tidb-components.) is enabled，and I want to access PD API, it is required to specify the client certificate. TiDB Dashboard can be integrated into PD.  So if I want to access Dashboard Core API through PD's endpoint, TiDB Dashboard should support TLS as well. Dashboard should inherit TL config from PD.
It would be great if TiDB Dashboard could support it before March 12, 2020.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by breeswish** [comment]
Supported by #195
