### ISSUE TITLE
support TLS when TLS authentication between the MySQL client and TiDB server is enabled

### ISSUE THREAD

**Issue by LinuxGit** [pingcap-incubator/tidb-dashboard#177]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

If [TLS authentication between the MySQL client and TiDB server](https://github.com/pingcap/docs/blob/7a62321b3ce9318cbda8697503c920b2a01aeb3d/how-to/secure/enable-tls-clients.md) is enabled,  it is required to specify the client certificate when TiDB Dashboard wants to create sql connection to TiDB. For example, login and statement API need to create sql connection.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by breeswish** [comment]
Resolved by #219
