### ISSUE TITLE
UCP: Replace momentjs with dayjs

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#181]
## Description

Momentjs has some major problems like mutable API and heavy bundle size. We can switch to dayjs, which is also supported by ant design.

https://ant.design/docs/react/replace-moment
https://github.com/iamkun/dayjs

## Score

* 300

## Mentor(s)

* @baurine 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* React

**Comment by gauss1314** [comment]
Hi, I find `Replace momentjs with dayjs` require antd 4.0, but we use antd 3.x.

Because when use `import generatePicker from 'antd/es/date-picker/generatePicker';`, `generatePicker` is added since 4.0.

**Comment by breeswish** [comment]
@gauss1314 antd 3.x also supports dayjs and actually it is already using dayjs (see `config-overrides.js`, not verified).

**Comment by breeswish** [comment]
I'm updating the score to 300 now, since recently we removed the [antd-dayjs-webpack-plugin](https://github.com/ant-design/antd-dayjs-webpack-plugin) due to its compatibility issue with existing dayjs instances. One need to add it back and resolve these compatibility issues to work on this PR.

**Comment by Rustin-Liu** [comment]
I am working on this.
