### ISSUE TITLE
User interface ENG-CHN I18N review (phase 1: P0 part)

### ISSUE THREAD

**Issue by uglyengineer** [pingcap-incubator/tidb-dashboard#188]
User interface ENG-CHN I18N review (phase 1: P0 part)

demo: 
http://172.16.5.39:10131/dashboard/#/cluster_info   （u=root；p为空；直接点击登陆即可）

to be reviewed: 
1. https://github.com/pingcap-incubator/tidb-dashboard/tree/master/ui/src/apps/clusterInfo/translations
2. https://github.com/pingcap-incubator/tidb-dashboard/tree/master/ui/src/apps/diagnose/translations
3. https://github.com/pingcap-incubator/tidb-dashboard/tree/master/ui/src/apps/keyvis/translations
4. https://github.com/pingcap-incubator/tidb-dashboard/tree/master/ui/src/apps/logSearching/translations
5. https://github.com/pingcap-incubator/tidb-dashboard/tree/master/ui/src/apps/nodeProfiling/translations
6. https://github.com/pingcap-incubator/tidb-dashboard/tree/master/ui/src/apps/statement/translations
7. https://github.com/pingcap-incubator/tidb-dashboard/tree/master/ui/src/layout/translations

related issue: https://github.com/pingcap-incubator/tidb-dashboard/issues/36

**Comment by breeswish** [comment]
@lilin90 PTAL

**Comment by lilin90** [comment]
@breeswish Got it.

**Comment by lilin90** [comment]
The 5th one to be reviewed is updated to: https://github.com/pingcap-incubator/tidb-dashboard/tree/master/ui/src/apps/instanceProfiling/translations in #240.

**Comment by lilin90** [comment]
@breeswish Review done.
