### ISSUE TITLE
UI should work without Internet Connection

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#199]
## Feature Request

Considering the user scenario, the UI is likely to be run without an internet connection.

**Comment by baurine** [comment]
It makes sense, now it seems only the diagnosis report depends on the external CSS and js files from CDN, we should put them in local, but we need to consider how to build them in the go binary as well.

**Comment by breeswish** [comment]
@baurine Yes. This need to be carefully designed.

**Comment by baurine** [comment]
This issue can be closed after #307 is merged.
