### ISSUE TITLE
UCP: Add left navigations for diagnosis report

### ISSUE THREAD

**Issue by baurine** [pingcap-incubator/tidb-dashboard#200]
## Description

When the diagnosis report is too long, it will cost some time in jumping between different sections, so this task is to add navigations in the diagnosis report left side for easily jumping.

![WeChatWorkScreenshot_f85e8cf8-9cc7-464a-bce4-d0f12dc7d6c9](https://user-images.githubusercontent.com/1284531/76393824-4ff36800-63af-11ea-80da-e4492485926c.png)

## Score

* 50

## Mentor(s)

* @baurine 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* HTML
* Go Template

**Comment by STRRL** [comment]
@baurine 

Hi, I need a more clearly demand. 

I found there are some fields that all have a meaning about title:

Category: It's a array of string. It will be used to generate `h1` tag.
Ttitle: As the name say, it's the title.

Which one should I use?

Also I need choose one field, using as HTML `anchor`, for navigator jumping.

**Comment by baurine** [comment]
Hi @STRRL , the title is what you need, but if you can combine the category and title together that would be better.
