### ISSUE TITLE
refine privileges management

### ISSUE THREAD

**Issue by LinuxGit** [pingcap-incubator/tidb-dashboard#209]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

TiDB Dashboard's RBAC is based on TiDB user privileges. Currently we need to use the root user. We can use ordinary users, and grant necessary privileges, advoid using root user.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by gregwebs** [comment]
I suggest we create a separate user for the dashboard. This also avoids having to store the user password in the dashboard system (even if it is stored in an encrypted form).

The "dashboard" user would only have permissions for the operations it needs to do. These operations are specified by the "dashboard" role. A user logs in to the dashboard with their MySQL user (the dashboard makes a MySQL connection). Their MySQL user must have the "dashboard" role. If it does, they are logged in to the dashboard and they are given back a session token. The dashboard no longer needs their password: for all its connections besides the initial user login, it uses its own dashboard user. The dashboard stores its password in program memory, and this password must be given by the deployment.

This technique does not require any storage of the user password, just of the dashboard password, and the dashboard role used can have it's permissions limited.

**Comment by gregwebs** [comment]
@breeswish can you add this to the security project?

**Comment by gregwebs** [comment]
This is still very relevant.

**Comment by breeswish** [comment]
Opened a formal feature request: https://github.com/pingcap-incubator/tidb-dashboard/issues/560
