### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by gregwebs** [pingcap-incubator/tidb-dashboard#216]
I see a lot of `fmt.Sprintf` for SQL queries and am concerned about the possibility of SQL injection. Of course, this only matters once the dashboard support non-root user login.

Please add this to the Security project.

**Comment by breeswish** [comment]
@gregwebs Thanks for the concern. PR https://github.com/pingcap-incubator/tidb-dashboard/pull/176 is resolving the only SQL injection risk remaining in the diagnose report functionality.

**Comment by breeswish** [comment]
Close the issue since after investigation we found that there is no user controllable raw SQL input. Although there were SQL string constructing, the parameters are from trusted source instead of user input.
