### ISSUE TITLE
Undefined error in /keyvis

### ISSUE THREAD

**Issue by Fullstop000** [pingcap-incubator/tidb-dashboard#217]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**
1. Use `tiup` start a nightly cluster
2. Start tidb-dashboard server
3. `npm start`
4. Open `localhost:3000`
5. Sign in
6. Click "热点可视化"
7. Move mouse to the x vertical label

**What did you expect to see?**

**What did you see instead?**
![image](https://user-images.githubusercontent.com/12471960/76677385-ac04f900-6608-11ea-8a39-76207bc50f12.png)

Detailed error trace:
```
TypeError: Cannot read property 'labels' of undefined
getTooltipOverviewLabel
src/apps/keyvis/heatmap/chart.ts:579
  576 | }
  577 | 
  578 | const leftLabel = data.keyAxis[keyIdx]!.labels
> 579 | const rightLabel = data.keyAxis[keyIdx + 1]!.labels
      | ^  580 | if (!leftLabel && !rightLabel) {
  581 |   return []
  582 | }
```
![image](https://user-images.githubusercontent.com/12471960/76677403-d656b680-6608-11ea-92c0-7d627fdfb539.png)

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**
```
Release Version: ui_release_20200306_1-14-g1a9cde3-dirty
Git Commit Hash: 1a9cde30432cd890fae7df465713e4fe3c7335ef
Git Branch: master
```

**Comment by breeswish** [comment]
I guess this is duplicated to https://github.com/pingcap-incubator/tidb-dashboard/issues/213
