### ISSUE TITLE
UCP: KeyVis: Support to display DB Name

### ISSUE THREAD

**Issue by HunDunDM** [pingcap-incubator/tidb-dashboard#247]
## Description

Currently, the label information displayed by Key Visualizer includes only the table name and index name. Since tables with the same name may exist in different DBs, we need to display the DB Name to distinguish them.

## Score

* 50

## Mentor(s)

* @hundundm

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang

**Comment by breeswish** [comment]
Implemented by #274
