### ISSUE TITLE
Support TiFlash in Dashboard

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap-incubator/tidb-dashboard#268]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I want to add something about TiFlash in tab "Cluster Info".

**Describe the feature you'd like:**

I have try to add API for getting TiFlash nodes' info from PD. But I don't know how to verify it, nor about how to show it in UI.

https://github.com/JaySon-Huang/tidb-dashboard/commit/39e90d18706acc3627ad060290e0284622ac2c39

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

In PD, we can get TiFlash nodes with "engine"="tiflash" in store.labels.
`http://127.0.0.1:6506/pd/api/v1/stores`
```
{
  "count": 2,
  "stores": [
    {
      "store": {
        "id": 1,
        "address": "127.0.0.1:7506",
        "version": "4.1.0-alpha",
        "status_address": "127.0.0.1:16506",
        "git_hash": "3d6ebd48dd0cd49f51919b15d04216c8c51219ae",
        "start_timestamp": 1584783334,
        "binary_path": "xxx/tikv/tikv-server",
        "last_heartbeat": 1584784534378725000,
        "state_name": "Disconnected"
      },
      "status": {
        ...
      }
    },
    {
      "store": {
        "id": 44,
        "address": "127.0.0.1:9506",
        "labels": [
          {
            "key": "engine",
            "value": "tiflash"
          }
        ],
        "version": "4.1.0-alpha",
        "peer_address": "127.0.0.1:9006",
        "last_heartbeat": 1584789939191551000,
        "state_name": "Up"
      },
      "status": {
       ...
      }
    }
  ]
}
```

**Comment by breeswish** [comment]
I see that tiflash node is identified by using "engine" label. What will happen if user self-defined an engine label?

**Comment by JaySon-Huang** [comment]
We can't prevent user from doing that now. Maybe later @disksing have better support on PD.
By now, tidb, br, lightning use this "engine" label to distinguish tiflash stores from tikv stores.

**Comment by breeswish** [comment]
Got it. 

- What kind of states will tiflash nodes hold? Does it provide the same states as normal TiKV nodes? 
- Is it possible to add "binary_path" as well like normal TiKV nodes? We will need it to display it in the instance list.

**Comment by breeswish** [comment]
For your change in https://github.com/JaySon-Huang/tidb-dashboard/commit/39e90d18706acc3627ad060290e0284622ac2c39#diff-ddfdd955cde4e3e6db6bf319dd2bc1cfR190 I think you'd better change this method to output both TiKV and TiFlash topology.
