### ISSUE TITLE
UCP: Improve build packages

### ISSUE THREAD

**Issue by baurine** [pingcap-incubator/tidb-dashboard#269]
## Description

Recently we refactored the frontend part files structure to monorepo mode, related PRs: #215 , #253 , #254 , but the refactor is not perfect, remains some issues:

1. the rollup.config.js is duplicated in each package, we need to unify to one rollup.config.js
1. there are some new added or modified less vars in config-overrides.js, for example:

    ```
    addLessLoader({
      javascriptEnabled: true,
      modifyVars: {
        '@primary-color': '#3351ff',
        '@body-background': '#f0f2f5',
      },
      globalVars: {
        '@padding-page': '48px',
      }
    }),
    ```

    we need to manually copy to rollup.config.js to keep them same, for example:

    ```
    postcss({
      extensions: ['.less'],
      use: [
        [
          'less',
          {
            javascriptEnabled: true,
            modifyVars: {
              '@primary-color': '#3351ff',
              '@body-background': '#f0f2f5',
            },
            globalVars: {
              '@padding-page': '48px', // TODO: keep same with root project
            },
          },
        ],
      ],
    }),
    ```
    
    we need to extract this part configuration in the same place.

## Score

* 300

## Mentor(s)

* @baurine 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Webpack
* Rollup

**Comment by breeswish** [comment]
Hint, another (better) solution is to use one build systems instead of two.
