### ISSUE TITLE
User interface ENG-CHN I18N review (report part)

### ISSUE THREAD

**Issue by uglyengineer** [pingcap-incubator/tidb-dashboard#289]
User interface ENG-CHN I18N review (phase 1: P0 part)

demo:
http://172.16.5.143:2379/dashboard/ （u=root；p为空；直接点击登陆即可）

to be reviewed:
Report demo 里面各项标题、说明、表头的英文表达，可以使用下方的 report demo 为模版；另附已有的中英文对照说明和一些中文说明：

report demo：（demo环境有问题，待补充）

1. 报告说明(报告内容是2.3.3部分)：https://github.com/pingcap-incubator/tidb-in-action/blob/master/session3/chapter2/diagnosis-report.md
2. 报告样例及中文标示说明（第14页开始）：https://docs.google.com/document/d/1b8o6GQCUVmSPT_EZHaZhKlb-jCMJ5KxTkDlkTrsFgQo/edit?pli=1#heading=h.9iz9gssqkj5k

**Comment by lilin90** [comment]
Start to review [diagnoseReportApp/translations/zh-CN.yaml](https://github.com/pingcap-incubator/tidb-dashboard/blob/master/ui/diagnoseReportApp/translations/zh-CN.yaml) and [diagnoseReportApp/translations/en.yaml](https://github.com/pingcap-incubator/tidb-dashboard/blob/master/ui/diagnoseReportApp/translations/en.yaml) on Apr 24 according to Weiwei WANG's latest request on Apr 23.

**Comment by breeswish** [comment]
Corresponding PRs are merged, closing the issue.
