### ISSUE TITLE
Polish I18N translations

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#36]
Currently I18N translation is written casually. We need to polish these translations.

**Comment by baurine** [comment]
Almost done:
- support i18n for left nav menus
- support i18n for statement

will submit the PR after statement PR is merged, because the current branch is based statement branch.

![8](https://user-images.githubusercontent.com/1284531/75055163-7724eb00-550f-11ea-99a6-17023b274fad.gif)
