### ISSUE TITLE
Avoid referencing protobuf struct in model

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#364]
## Feature Request

**Is your feature request related to a problem? Please describe:**

referencing protobuf structs in gorm model is bad that it breaks the compatibility guarantee provided by protobuf. When there is compatible changes in protobuf, our db however will break.

**Describe the feature you'd like:**

Decouple DB models and protocol models.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Deardrops** [comment]
This issue fixed in #322
