### ISSUE TITLE
TopN statement sort result is incorrect

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#367]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

In overview page, the sorting is done at client side, which results in incorrect behaviour after TopN truncation, i.e. `Sort(Limit(result)) != Limit(Sort(Result))`

**Comment by baurine** [comment]
Oh, got it, that's a problem. How about we add a "visibleCount" prop to StatementTable, so we still can sort them in the client side?

**Comment by baurine** [comment]
fix in #369

**Comment by baurine** [comment]
btw, should we hide the TopN statements in the overview page if the statements feature is disabled?

**Comment by breeswish** [comment]
Fixed by #369

**Comment by breeswish** [comment]
@baurine Yeah, I think we should at least notify user that overview feature is off
