### ISSUE TITLE
Infinite retrying in log searching

### ISSUE THREAD

**Issue by Fullstop000** [pingcap-incubator/tidb-dashboard#372]
If the backend returns an error in log searching, the frontend will encounter an infinite retrying situation, which could be improved maybe.
![image](https://user-images.githubusercontent.com/12471960/79688635-12251180-8282-11ea-8743-6e1b768ad5a2.png)

**Comment by Deardrops** [comment]
What kind of error the backend report?

Maybe we should stop the poll when encounter error.

**Comment by Fullstop000** [comment]
![image](https://user-images.githubusercontent.com/12471960/79875222-eccc0b00-841b-11ea-8b35-aec90f786609.png)
It seems that the problem hasn't been solved
@Deardrops @breeswish

**Comment by Deardrops** [comment]
@Fullstop000 Thanks for report. I have a question, how to reproduction this bug?

**Comment by Fullstop000** [comment]
1. Search logs as normal
2. Refresh page without changing pathname

**Comment by Deardrops** [comment]
> 
> 
>     1. Search logs as normal
> 
>     2. Refresh page without changing pathname

@Fullstop000 I try this step by step, but cannot reproduction this bug.
Do you run in the master branch of tidb-dashboard?

**Comment by Fullstop000** [comment]
I meet this problem after updating from master. I’ll do some debugging later for this.

**Comment by Fullstop000** [comment]
Reproduced on master branch
