### ISSUE TITLE
Fail to request /api/statements/time_ranges

### ISSUE THREAD

**Issue by Fullstop000** [pingcap-incubator/tidb-dashboard#373]
Got en error in requesting `http://localhost:12333/dashboard/api/statements/time_ranges`

Is this a compatibility problem?

![image](https://user-images.githubusercontent.com/12471960/79688709-9aa3b200-8282-11ea-97b7-cb67a0fb614b.png)

**Comment by breeswish** [comment]
Looks like you need a latest TiDB

**Comment by Fullstop000** [comment]
Use nightly TiDB solves the promblem
