### ISSUE TITLE
Add prompt for not choosing a target in log search

### ISSUE THREAD

**Issue by Fullstop000** [pingcap-incubator/tidb-dashboard#375]
For now, we create a request to log search even without choosing an instance. It could be better to add a prompt for this.

![image](https://user-images.githubusercontent.com/12471960/79693736-0a279a80-829f-11ea-9455-fd08469e4267.png)

**Comment by breeswish** [comment]
maybe duplicate to https://github.com/pingcap-incubator/tidb-dashboard/issues/113?

**Comment by breeswish** [comment]
Resolved.
