### ISSUE TITLE
Remember Column Options

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#410]
## Feature Request

**Is your feature request related to a problem? Please describe:**

![image](https://user-images.githubusercontent.com/1916485/80002181-e60fc780-84f1-11ea-96eb-a9b2f14aa520.png)

We can remember column options in local storage so that user don't need to repeatedly set it.

**Comment by baurine** [comment]
Got, realized yesterday as well, will figure it out today.
