### ISSUE TITLE
Remember Query Parameters by Session

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#411]
## Feature Request

**Is your feature request related to a problem? Please describe:**

For query parameters, they can be remembered in Session Storage (instead of Local Storage), so that it suffers from refresh, as well as history go back.

![image](https://user-images.githubusercontent.com/1916485/80002364-1f483780-84f2-11ea-91de-b670aa78a786.png)

It should not be stored in local storage, to avoid user being trapped (e.g. repeatly meeting errors) with some irregular settings. When storing in session storage, user can at least close, open browser again to restore.

**Comment by baurine** [comment]
Good idea!
