### ISSUE TITLE
Statement & Slow Query Integration

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#412]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We can display slow queries in the selected statement time range (& schema & plans).

**Comment by baurine** [comment]
How is it looks like?

**Comment by breeswish** [comment]
@baurine Good question! We can add another section in the statement detail page, which simply display a slow query table:

![image](https://user-images.githubusercontent.com/1916485/80305111-6fbede00-87ed-11ea-9f77-6c204e447bed.png)

Notice that, the detail page has a plan selection, thus we should only display slow queries in selected execution plans. This is currently not implemented in backend.

**Comment by baurine** [comment]
Got it!
