### ISSUE TITLE
Use <Result> Component

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#422]
## Feature Request

https://ant.design/components/result/

We can use the Result component comes from Ant Design in KeyViz and Statement when corresponding switch is closed

**Comment by baurine** [comment]
nice! will update it. (why I didn't see it when I tried to find a similar component...

**Comment by breeswish** [comment]
@baurine There are too many, I face the same problem as you in many times.
Remember to checkout our TODO list in Google spreadsheet first, since we have some more important tasks to do in this week :)
