### ISSUE TITLE
UCP: KeyViz: Support to label Key by separator when in KV mode

### ISSUE THREAD

**Issue by HunDunDM** [pingcap-incubator/tidb-dashboard#440]
## Description

Currently, Key Visualizer supports obtaining Table information of Key from TiDB. We need to be able to label Key according to the separator when TiKV is used independently. Only the back-end part needs to be implemented, and the label mode and separator can be modified by the dynamic config.

## Score

* 200

## Mentor(s)

* @hundundm 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang

**Comment by zzh-wisdom** [comment]
@HunDunDM  PTAL
