### ISSUE TITLE
Try to use esbuild to build frontend to shorten the build time (experiment)

### ISSUE THREAD

**Issue by baurine** [pingcap-incubator/tidb-dashboard#470]
Refs:

- [esbuild](https://github.com/evanw/esbuild)
- [esbuild-loader](https://github.com/egoist/esbuild-loader)

**Comment by baurine** [comment]
Did a try in https://github.com/pingcap-incubator/tidb-dashboard/commit/139b06e904bc52bff2d77e97a3ed8805b6a07065 but unfortunately failed, report errors when parsing bundle assets:

```
Error parsing bundle asset ".../build/static/js/0.df163045.chunk.js": no such file
Error parsing bundle asset ".../build/static/js/1.ab303cfe.chunk.js": no such file
Error parsing bundle asset ".../build/static/js/11.7c137ba2.chunk.js": no such file
Error parsing bundle asset ".../build/static/js/12.9a6799eb.chunk.js": no such file
Error parsing bundle asset ".../build/static/js/13.a4ecc160.chunk.js": no such file
Error parsing bundle asset ".../build/static/js/14.78ed2e9d.chunk.js": no such file
...
```

submit an issue in https://github.com/egoist/esbuild-loader/issues/5

**Comment by breeswish** [comment]
Esbuild claims to be 100x times faster, however it can only bundle script files. If Esbuild is used together with Webpack, then the performance improvements will be highly reduced because time cost tasks like bundling and minifying are still using Webpack.

**Comment by baurine** [comment]
> Esbuild claims to be 100x times faster, however it can only bundle script files. If Esbuild is used together with Webpack, then the performance improvements will be highly reduced because time cost tasks like bundling and minifying are still using Webpack.

I think so.

**Comment by breeswish** [comment]
Maybe we can leave it open to keep an eye on its future development :)

**Comment by egoist** [comment]
yes I don't expect much performance gain but we can use esbuild to minify code as well.

**Comment by egoist** [comment]
someone did a bench btw https://github.com/Rugvip/ts-build-bench

**Comment by breeswish** [comment]
To improve dev build speed, snowpack might be another good choice.

**Comment by breeswish** [comment]
Still relavant.
