### ISSUE TITLE
UCP: Drop react-spring

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#472]
## Description

React-spring animation is slow when there are a lot of SQL in SQL statement table list. Maybe it's better to drop react-spring and use some substitutions.

Antd's own animation component looks to be a good choice.

## Score

* 2091

## Mentor(s)

* @breeswish

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* CSS
* ReactJs
* Antd

**Comment by SSebo** [comment]
Replace `react-spring` with [`ant-motion`](https://motion.ant.design/) ?

**Comment by breeswish** [comment]
@ssebo Need to do experiments.

**Comment by breeswish** [comment]
Still relevant.

**Comment by breeswish** [comment]
We now have very minimal usage of react-spring.
