### ISSUE TITLE
UCP: Dashboard cannot run in Node 13+

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#487]
## Description

Currently Dashboard cannot run in Node 13+

## Score

* 301

## Mentor(s)

* @baurine 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Nodejs

**Comment by you06** [comment]
The score has been fixed.
