### ISSUE TITLE
Provide remove TiDB topology API

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#49]
When TiDB node is removed, its topology remains. We need to allow user hide specific TiDB node from the topology. If the TiDB node is still alive, this operation should not be allowed. If the TiDB node is partitioned, the TiDB itself should be able to re-add the topology back when partition ends.

**Comment by mapleFU** [comment]
https://github.com/pingcap/tidb/pull/14809/ add a ttl and none ttl node
* /topology/tidb/ip:port/ttl is a ttl key
* /topology/tidb/ip:port/tidb is a non ttl key ,but if it's deleted, etcd will watch this change and re-add it to tidb.
