### ISSUE TITLE
Do not produce slow log archive if there is no slow log

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#492]
## Bug Report

![image](https://user-images.githubusercontent.com/1916485/81890960-d3148280-95d9-11ea-9536-3c8889fe7704.png)

Now we will have an empty slow log archive even if there is no slow log. This is pretty confusing.

**Comment by Fullstop000** [comment]
![image](https://user-images.githubusercontent.com/12471960/82112417-6804b080-977f-11ea-9026-28d9fe9f34d6.png)
Maybe the UI should also disable downloading if there is no searching result?

**Comment by breeswish** [comment]
Good idea! @fullstop000 I can open a UCP, would you like to work on it?
