### ISSUE TITLE
Customization of dashboard when used as iframe

### ISSUE THREAD

**Issue by sivagao** [pingcap-incubator/tidb-dashboard#535]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

use iframe' src url params to indicate : 

 - hide the side-menu(headless)
 - inject auth token to dashboard

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by baurine** [comment]
Maybe we can add a new entry for iframe usage likes `dashboardApp` and `diagnoseReportApp` which only includes statements and slow query features?

**Comment by breeswish** [comment]
After discussion with @sivagao we have two solutions:
- Implement a portal page, which accept frontend configurations like apiPrefixPath, isHeadlessMode and so on. These configurations are then saved in localStorage.
- Add new configuration items in the backend and then passed to frontend. This is more complex but looks to be more secure.

**Comment by breeswish** [comment]
See also https://github.com/pingcap-incubator/tidb-dashboard/issues/554
