### ISSUE TITLE
Requirement Request: Replication Status Page

### ISSUE THREAD

**Issue by baurine** [pingcap-incubator/tidb-dashboard#548]
## Description

Related project: Dashboard

Introduce an overview page for all stores' replication status (See #546) to TiDB Dashboard.

## Category

* Feature
* Usability

## Value

This can help drop the necessity of using PD-ctl region APIs. 

- Score: 3

## Workload Estimation

10 Person Day

**Comment by breeswish** [comment]
Close for #686
