### ISSUE TITLE
Requirement Request: TiDB Connections and Running SQLs - Execution Time of Running SQLs

### ISSUE THREAD

**Issue by baurine** [pingcap-incubator/tidb-dashboard#550]
## Description

Related project: TiDB, TiKV

Background: For long-time running SQLs, users don’t know why they spend so much time running until the SQL is really finished. Additionally, in the process list table, users can only view SQL elapsed time, which contains both waiting time and execution time. This makes it hard to figure out the real SQL that causes problems. Providing on-CPU time and wait time could be very helpful.

*Implementation detail is not yet decided.*

## Category

* Feature
* Usability

## Value

This can be very helpful for the users to understand what happened for long-time running SQLs. 

- Score: 5

## Workload Estimation

30 Person Day

**Comment by breeswish** [comment]
Related: https://github.com/pingcap/tidb/issues/17692

**Comment by breeswish** [comment]
Close for pingcap/tidb#17692
