### ISSUE TITLE
Requirement Request: Add Latency Quantiles in Statement

### ISSUE THREAD

**Issue by crazycs520** [pingcap-incubator/tidb-dashboard#557]
## Description

Related projects: TiDB

Currently, the statement only has `min`,`avg`,`max`,`sum` value of time latency. This issue wants to add quantiles time (like 99% Query Time).
 
## Category

* Feature
* Usability

## Value

Now only avg, max and min latency are displayed, which is usually not enough for real-world scenarios. Quantile based latencies (like 99% duration) need to be added. 

- Score: 5

## Workload Estimation

15 Person Day

**Comment by breeswish** [comment]
Related feature request in TiDB: https://github.com/pingcap/tidb/issues/17621
