### ISSUE TITLE
Requirement Request: Record Parameter Values for Parameterized Queries

### ISSUE THREAD

**Issue by crazycs520** [pingcap-incubator/tidb-dashboard#563]
## Description

Related project: TiDB

When users are sending parameterized queries, the parameter values are not recorded at all in Statements system tables. We can record these parameters.

## Category

* Feature
* Usability

## Value

This makes it impossible to reproduce the sample SQL.

- Score: 4

## Workload Estimation

7 Person Day

**Comment by breeswish** [comment]
Related: https://github.com/pingcap/tidb/issues/17690
