### ISSUE TITLE
Requirement Request: Data Export in statement

### ISSUE THREAD

**Issue by crazycs520** [pingcap-incubator/tidb-dashboard#565]
## Description

 The data of Statement UI is a complex aggregation of fields in statement tables. Since the query is usually hard to write manually, users are not easy to get these data. Thus for data in UI it should be allowed to be exported.

## Category

* Feature
* Usability

## Value

- Score: 3

## Workload Estimation

10 Person Day

**Comment by baurine** [comment]
Start to work on this. 

Some questions:

- What's kind of format for it to export? Is .csv ok?
- Export all fields or just the selected fields?

**Comment by baurine** [comment]
Will do it after the PR #749 is merged to avoid conflicts.
