### ISSUE TITLE
Requirement Request: Diagnostics Report: Visualize Metric Relations

### ISSUE THREAD

**Issue by crazycs520** [pingcap-incubator/tidb-dashboard#566]
## Description

Generate a TiDB dababase pprof just like golang pprof, base in time cost in each module, such as :

* total time
* avg time
* P999 time
* P99 time

And we can put some related information together, such as `pool-size` config value.

![image](https://user-images.githubusercontent.com/26020263/83118021-641e4a00-a100-11ea-8ffb-155ee9d2c95c.png)

## Category

* Feature

* Usability

## Value

The pprof is more understandable and put information together is better for usage.

- Score: 4

## Workload Estimation

40 Person Day

**Comment by breeswish** [comment]
This feature is already implemented.
