### ISSUE TITLE
v4.0.0 dashboard diagnose report error

### ISSUE THREAD

**Issue by Win-Man** [pingcap-incubator/tidb-dashboard#586]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

部署 4.0.0 版本集群，通过 dashbaord 生成性能诊断报告，发现报告最下面有错误
![image](https://user-images.githubusercontent.com/12085878/83390514-91cb0200-a424-11ea-9b7b-e22e0a74fa28.png)

**What did you expect to see?**

**What did you see instead?**

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**
![image](https://user-images.githubusercontent.com/12085878/83390578-ac04e000-a424-11ea-96e0-e36149b33c76.png)

![image](https://user-images.githubusercontent.com/12085878/83390597-b7f0a200-a424-11ea-8e2e-7b7146843882.png)

**Comment by crazycs520** [comment]
No, Still in cherry-pick PR

**Comment by breeswish** [comment]
@crazycs520 Could you reference the PR here so that we can track the progress?

**Comment by crazycs520** [comment]
Need pick https://github.com/pingcap/tidb/pull/15589,

But should wait https://github.com/pingcap/tidb/pull/17671 (cherry-pick #15985) first.
