### ISSUE TITLE
In-consistent i18n

### ISSUE THREAD

**Issue by Fullstop000** [pingcap-incubator/tidb-dashboard#588]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**
1. Go to `/diagnose`
2. Click `开始` Button 

**What did you expect to see?**

`'rangeBegin' is required` should be in Chinese

**What did you see instead?**

![image](https://user-images.githubusercontent.com/12471960/83416469-47ad4500-a453-11ea-8517-33a0dfbe01f5.png)

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**
master

**Comment by breeswish** [comment]
It is a problem in all form check items, we need an elegant way to fix it.

**Comment by ericsyh** [comment]
i will try to fix this issue.

**Comment by breeswish** [comment]
Looks like this can be resolved by using [ConfigProvider](https://ant.design/components/config-provider-cn/)
