### ISSUE TITLE
Wrong redirect when accessing http://localhost:2379/dashboard/

### ISSUE THREAD

**Issue by danparisi** [pingcap-incubator/tidb-dashboard#609]
I'm a running tidb cluster as explained here:
https://pingcap.com/docs/tidb-in-kubernetes/dev/access-dashboard/

But when I try to see the dashboard, after port-forwarding pd service, I get redirected here:
http://tidb-cluster-pd-1.tidb-cluster-pd-peer.dan.svc:2379/dashboard/

_Note that:_
Namespace: dan
Cluster name: tidb-cluster

**What did you do?**
`
$ kubectl port-forward svc/tidb-cluster-pd 2379:2379
`

Then I tried to reach this address:
`
http://localhost:2379/dashboard/
`

But I got redirected here:
`
http://tidb-cluster-pd-1.tidb-cluster-pd-peer.dan.svc:2379/dashboard/
`

And of course, I got a 404

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**
Cluster version: 1.1
TiDb version: 4.0.0

**Comment by breeswish** [comment]
Thanks for the report! Did you run multiple PD instances?

**Comment by danparisi** [comment]
Yes, I've 3 instances:
```
k get pods | grep tidb-cluster-pd
tidb-cluster-pd-0                                            1/1     Running     0          40m
tidb-cluster-pd-1                                            1/1     Running     0          42m
tidb-cluster-pd-2                                            1/1     Running     0          42m
```

**Comment by Yisaer** [comment]
@danparisi  Hi, this error have been tracked in https://github.com/pingcap/tidb-operator/issues/2650. Thanks for reporting.

**Comment by breeswish** [comment]
@danparisi Currently there are still some problems when multiple PD instances are deployed, as the issue tracked above. If you would like to simply play with TiDB Dashboard, you may try to deploy only 1 PD instance. Thanks again for the report!

**Comment by danparisi** [comment]
Okay thanks!
Just want to point that I'm not currently using an Ingress (as mentioned on bug 2650) but just port-forwarding

**Comment by breeswish** [comment]
Good to know! The description of the original issue is not complete. Users may suffer from the problem even if Ingress is not used (the solution in that issue should be universal, i.e. also solve your case after implemented)

**Comment by danparisi** [comment]
Thanks, I'll wait for v4.0.1 to be released then :)
