### ISSUE TITLE
search_logs: Always return empty result

### ISSUE THREAD

**Issue by baurine** [pingcap-incubator/tidb-dashboard#665]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

1. Click "Search Logs" link on the left side menu to enter the search logs app.
1. Choose "Recent 4 week" as time range, remain others with the default value
1. Click "Search" button to start searching logs

**What did you expect to see?**

A non-empty table

**What did you see instead?**

An empty result table

![image](https://user-images.githubusercontent.com/1284531/86217053-826cdf00-bbb1-11ea-9619-fb705482c9b2.png)

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

Tried TiDB v4.0.0 , v4.0.1, nightly by `tiup playground v4.0.0|v4.0.1|nightly --tiflash 0` command. All have this issue.

**Comment by breeswish** [comment]
Looks to be a playground issue. We need further investigation. Would like to keep tracking on this problem? @baurine

**Comment by baurine** [comment]
Sure.

**Comment by baurine** [comment]
Some investigation results by using `tiup-cluster` to deploy the cluster.

**Works fine in an old v4.0.0-rc cluster**

![企业微信20200702110111](https://user-images.githubusercontent.com/1284531/86324051-857ad480-bc70-11ea-9fff-50a4f50bdead.png)

![企业微信20200702110054](https://user-images.githubusercontent.com/1284531/86324048-83187a80-bc70-11ea-875c-3bcf0be1b881.png)

**Works fine in v4.0.0**

![企业微信20200702022340](https://user-images.githubusercontent.com/1284531/86324134-ab07de00-bc70-11ea-9e03-c1626e7a706b.png)

![企业微信20200702022328](https://user-images.githubusercontent.com/1284531/86324125-a93e1a80-bc70-11ea-82ac-b6180575810b.png)

**Comment by baurine** [comment]
Contiue to try v4.0.1 and nightly.

**Comment by baurine** [comment]
After testing, it works fine in v4.0.1 and nightly as well.

**Comment by baurine** [comment]
The reason is that the playground outputs some illegal format logs to the log file. Submit an issue for tiup: https://github.com/pingcap/tiup/issues/570
