### ISSUE TITLE
Search log: TiFlash instances cannot be displayed in select component

### ISSUE THREAD

**Issue by leiysky** [pingcap-incubator/tidb-dashboard#669]
## Bug Report

**What did you do?**

Try to search log on TiFlash nodes.

**What did you expect to see?**

TiFlash instance should display in the select component.

**What did you see instead?**

TiFlash instance disappeared.

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

Release Version: ui_release_20200619_3-9-g392fbac
Git Commit Hash: 392fbac08c76c8c47026cafa7c92149e5fac672d
Git Branch: master
UTC Build Time:  2020-07-02 11:05:57

**Comment by leiysky** [comment]
https://github.com/pingcap-incubator/tidb-dashboard/blob/4a764c1bdd4d0ada4731cc4a6adc465b8e0f910b/ui/lib/utils/instanceTable.ts#L65-L67

https://github.com/pingcap-incubator/tidb-dashboard/blob/4a764c1bdd4d0ada4731cc4a6adc465b8e0f910b/ui/lib/apps/SearchLogs/components/SearchHeader.tsx#L164-L168

https://github.com/pingcap-incubator/tidb-dashboard/blob/4a764c1bdd4d0ada4731cc4a6adc465b8e0f910b/ui/lib/components/InstanceSelect/index.tsx#L152-L167

It seems that TiFlash instances will never be displayed since `InstanceSelect.props.enableTiFlash` is `undefined`.

**Comment by baurine** [comment]
Got, will have a look later.
