### ISSUE TITLE
Optimize Telemetry config

### ISSUE THREAD

**Issue by HunDunDM** [pingcap-incubator/tidb-dashboard#670]
## Feature Request

**Describe the feature you'd like:**

* Rename `DisableTelemetry` to `EnableTelemetry`, consistent with TiDB. (The corresponding config of PD needs to be updated.)
* In TiDB mode, support to use SQL to obtain the telemetry status of TiDB as a serial switch.

**Describe alternatives you've considered:**

* Supports dynamic configuration of Telemetry. (Only when both `Config.Telemetry` and `TiDB.Telemetry` are Enable.)

**Teachability, Documentation, Adoption, Migration Strategy:**

[Telemetry](https://docs.pingcap.com/tidb/v4.0/telemetry#disable-telemetry)

**Comment by baurine** [comment]
> In TiDB mode, support to use SQL to obtain the telemetry status of TiDB as a serial switch.

Hi @HunDunDM , what does this mean?
