### ISSUE TITLE
i18n: the default language value is incorrect 

### ISSUE THREAD

**Issue by ericsyh** [pingcap-incubator/tidb-dashboard#675]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

I setup the TiDB Dashboard environment then signed in and go to the Setting page. 

**What did you expect to see?**

The **Language & Location** value should be **简体中文** or **English**. 

**What did you see instead?**
I got **zh** instead. 

![image](https://user-images.githubusercontent.com/10498732/86870706-79c55d00-c10b-11ea-826b-f56a4d492399.png)

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

The latest version: 
```
Release Version: ui_release_20200619_3-14-g00bca6f
Git Commit Hash: 00bca6f05d8e3d348a2b530204d6c4929140e7b8
Git Branch: master
UTC Build Time:  2020-07-08 01:44:05
```

**Comment by breeswish** [comment]
This is not an expected behaviour. @baurine PTAL if you are free

**Comment by baurine** [comment]
Ahh, looks weird, I even can't find the `zh` keyword in the source code... What's your browser version and system? Does it display correctly after refreshing the browser?

**Comment by baurine** [comment]
I guess the language code i18next get from the browser is 'zh' instead of 'zh-CN'. We need to refine it. @ericsyh Would you like to help check what's the value of `i18n.language` in the `ui/lib/apps/DashboardSettings`?

**Comment by baurine** [comment]
I changed my browser language to 'zh-TW', get a 'zh-TW' option in language selector, and a whole page with the English language.

![image](https://user-images.githubusercontent.com/1284531/87000422-9cc53f00-c1e7-11ea-93e5-5589e10af03b.png)
