### ISSUE TITLE
Setting statement collect interval result in loading spinner

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#678]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

Set statement collect interval to a smaller value.

**What did you expect to see?**

Updated and the right panel disappear.

**What did you see instead?**

![image](https://user-images.githubusercontent.com/1916485/87034530-88e70080-c21a-11ea-8495-abdcfbd0c57a.png)

The spinner keep spinning.

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

**Comment by baurine** [comment]
Tested it and not easy to re-produce, keep an eye on it. And we need to and will polish the error handle.
