### ISSUE TITLE
`yarn build:library` doesn't work anymore

### ISSUE THREAD

**Issue by baurine** [pingcap-incubator/tidb-dashboard#685]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

Run `yarn build:library` command in the `ui` folder to build the library.

**What did you expect to see?**

Build successfully.

**What did you see instead?**

Build failed. 

It said can't find `.package_release_version` file which is mis-deleted in PR #679 . Adding this file back can resolve this issue.   

Because DBass doesn't need the library anymore, do we need to remove it or still keep it for the future usage (likes for the plugin? maybe) @breeswish 

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

master branch.

**Comment by breeswish** [comment]
Yes, it should be removed. I forget to remove this command in https://github.com/pingcap-incubator/tidb-dashboard/pull/679

**Comment by baurine** [comment]
Got, will remove it later.
