### ISSUE TITLE
Visualize Location Topology

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#688]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Users may mis-configure location labels. This problem can be easily discovered if we provide a UI to visualize the topology.

**Describe the feature you'd like:**

Add a new web page, which visualizes store location labels.

Labels can be visualized using [Tree-Graph](https://observablehq.com/@d3/collapsible-tree) as:

![image](https://user-images.githubusercontent.com/1916485/87408587-4183ba00-c5f6-11ea-8c52-b419ed3f47d0.png)

Different colors can be assigned to better distinguish from labels and stores.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

Notes:

1. Stores have different kind of labels. Besides location labels, there could also be label `engine = tiflash`, which need to be filtered out.

2. Starting from PD v4.0.0, PD supports Placement Rules. When Placement rules are specified, the location labels configuration from PD might not be reliable since it can be overridden by placement rules. To resolve this issue, we may fetch all placement rules and check whether location label orders in the placement rules conflicts with the rules defined in PD configuration. If there is a conflict, the visualization should stop.

**Comment by baurine** [comment]
Hi @breeswish @HunDunDM could you please attach some related docs / issues / PRs here if it has, thanks!

**Comment by breeswish** [comment]
The visualization should be based on location labels.

Documentation (Chinese) about the "location label": https://pingcap.com/docs-cn/stable/schedule-replicas-by-topology-labels/

In v4.0.0, there are also non-location labels, which should be ignored.
