### ISSUE TITLE
Move query parameters to URL query part

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#701]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now we have telemetry feature, which records the URL part without `?xxx`. However since some query parameters are placed in paths, like `/search_logs/details/:id`, this makes it not possible to group such URLs together.

**Describe the feature you'd like:**

Move all query parameters to the URL query part.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by baurine** [comment]
Will research how others do analytics when using a restful style URL.

**Comment by breeswish** [comment]
We need to prioritize the implementation of this issue since v4.0.4 will release much earlier.

**Comment by baurine** [comment]
ok, will do it this week.
