### ISSUE TITLE
statement template contains redundant blank space between the method name and left brace

### ISSUE THREAD

**Issue by baurine** [pingcap-incubator/tidb-dashboard#704]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

View a statement detail information.

**What did you expect to see?**

**What did you see instead?**

![image](https://user-images.githubusercontent.com/1284531/88479010-fa46e300-cf7e-11ea-92e1-79be42ec9537.png)

statement template contains redundant blank space between the method name and left brace, which is a syntax error.

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

**Comment by breeswish** [comment]
After investigation, it is caused by https://github.com/pingcap/tidb/issues/18907
