### ISSUE TITLE
Support all fields in statement and slow query list

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#705]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

Now in statement and slow query UI, only part of the all available fields are listed. It would be better to allow users to select any possible columns.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by breeswish** [comment]
@baurine I think we can prioritize this improvement after current work is done.

**Comment by baurine** [comment]
ok, sure!

**Comment by baurine** [comment]
Start to work on this today.
