### ISSUE TITLE
Add action to check release version is changed for release branch

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#715]
## Feature Request

**Is your feature request related to a problem? Please describe:**

One may forget to update the release version file when doing a release.

**Describe the feature you'd like:**

Add a GitHub action to check it.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Howie59** [comment]
i received this 
"Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate."

**Comment by breeswish** [comment]
@Howie59 Labels are added, please take a look again, thanks!

**Comment by breeswish** [comment]
I believe this issue is resolved. Feel free to leave comments if there are remaining questions, thanks!
