### ISSUE TITLE
Support download prometheus snapshot as zip

### ISSUE THREAD

**Issue by lysu** [pingcap-incubator/tidb-dashboard#730]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Nowadays, our customer and dba often report issues with Grafana screenshot

but pictures make it hard to zoom in and zoom out or deep analyze metrics with more advance PromQL.

it wastes much time to communicate about choosen right time window or edit Granfana expression.

**Describe the feature you'd like:**

Prometheus supports capture snapshot and restore from the snapshot(see this https://www.robustperception.io/taking-snapshots-of-prometheus-data)

so, maybe we can let our customer or dba download Prometheus snapshot and give RD to quick restore metric data then analyze the problem remotely.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

`/admin/tsdb/snapshot` api only save snapshot in Prometheus's node, maybe need tiup to fetch it to dashboard to make user accessible?

https://www.robustperception.io/taking-snapshots-of-prometheus-data
https://suraj.io/post/how-to-backup-and-restore-prometheus/

**Comment by breeswish** [comment]
I am working on similar topics recently and the approach is to provide a Grafana snapshot instead of Prometheus snapshot to cover 90% use cases. A grafana snapshot is much lighter-weight (a dump of Prometheus data may take several GiB, when time range is not provided). The disadvantage is that some metrics not displayed in Grafana will not be displayed anyway after a snapshot.

**Comment by breeswish** [comment]
I opened a comprehensive feature request for implementing both Grafana exporting and Prometheus exporting. It can fulfill all kind of demands related to metrics exporting and loading / viewing (lightweight but Grafana expressions only, or heavyweight but full data).

Feel free to move discussions to https://github.com/pingcap-incubator/tidb-dashboard/issues/735. Thanks!
