### ISSUE TITLE
Add zoom and pan to store topology

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#737]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Current UI does not look pretty when user has large screen:

![image](https://user-images.githubusercontent.com/1916485/90612727-0733bb00-e23b-11ea-8909-627fc1a7107d.png)

While it is also hard to read when user screen is small:

![image](https://user-images.githubusercontent.com/1916485/90612820-2599b680-e23b-11ea-9d18-2c4601fe0e62.png)

**Describe the feature you'd like:**

Add support for zoom and pan for the graph. Initially, the visualization should display as 1:1 (the same font-size as the page) all nodes can be displayed, leaving some blanks. If not all nodes can be displayed, the graph is initially scaled-*out* to display a full view by default.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by baurine** [comment]
Got, will have a look.

**Comment by baurine** [comment]
Related PR: #719
