### ISSUE TITLE
Let API client initialize by default

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#738]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now we need to manually initialize the Api client, which is not convenient in tests or storybooks.

**Describe the feature you'd like:**

Let api client initialize itself.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by baurine** [comment]
Ok, got it!
