### ISSUE TITLE
Memorize open / close status in statements and slow queries

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#747]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Fields are closed by default, like Full SQLs, Execution Plans.

**Describe the feature you'd like:**

Maybe better to memorize these open / close status.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by baurine** [comment]
I don't understand it, according to the code, now we have remembered which columns show, and whether should show full SQL for statement and slow query. We persist them in the local storage.

```
  const [visibleColumnKeys, setVisibleColumnKeys] = useLocalStorageState(
    VISIBLE_COLUMN_KEYS,
    defColumnKeys
  )
  const [showFullSQL, setShowFullSQL] = useLocalStorageState(
    SHOW_FULL_SQL,
    false
  )
```

**Comment by breeswish** [comment]
@baurine I mean these ones

![image](https://user-images.githubusercontent.com/1916485/91710065-40164d00-ebb6-11ea-9c1b-7b0e3aca21ac.png)

**Comment by baurine** [comment]
Got it!
