### ISSUE TITLE
Dashboard show txn_start_ts value is  different from  tidb_slow_query.log 

### ISSUE THREAD

**Issue by yilongrong** [pingcap-incubator/tidb-dashboard#758]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

1. When I find tikv.log include slow-query information, I need use txn_start_ts value to find the sql.

[tracker.rs:199] [slow-query] [internal_key_skipped_count=970284] [internal_delete_skipped_count=0] [block_cache_hit_count=657] [block_read_count=0] [block_read_byte=0] [encrypt_data_nanos=0] [decrypt_data_nanos=0] 
[scan_first_range="Some(start: 7480000000000000715F728000000000277903 end: 7480000000000000715F72800000000036472F)"]
[scan_ranges=1] [scan_iter_processed=970284] [scan_iter_ops=970286] [scan_is_desc=false] [tag=select] [table_id=113] 
[txn_start_ts=**419447227966554113**] 
[handler_build_time=0ns] [snapshot_wait_time=1ms] 
[schedule_wait_time=0ns] [wait_time=1ms] [total_process_time=2.501s] 
[req_time=2.641s] [remote_host=ipv4:172.16.5.169:34238] [region_id=2113]

2. Dashboard show txn_start_ts  value is not correct. 

![image](https://user-images.githubusercontent.com/55389305/93053023-c5f7c500-f699-11ea-931f-c216cf8af3ac.png)

**What did you expect to see?**

Dashboard show txn_start_ts  value should same with slow query log.
![image](https://user-images.githubusercontent.com/55389305/93054024-48cd4f80-f69b-11ea-9c73-d1957bfe813a.png)

**What did you see instead?**

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

v 4.0.5

**Comment by baurine** [comment]
Thank you for your report, let me have a check.

**Comment by baurine** [comment]
It seems not easy to reproduce. hi @yilongrong , can you make sure the above two are the exact same slow query? For example the same time, the same SQL...

**Comment by breeswish** [comment]
I believe this issue can be fixed by https://github.com/pingcap-incubator/tidb-dashboard/pull/793
