### ISSUE TITLE
Overview page uses terms not mentioned in the docs

### ISSUE THREAD

**Issue by zhangysh1995** [pingcap-incubator/tidb-dashboard#779]
## Feature Request

**Is your feature request related to a problem? Please describe:**

![image](https://user-images.githubusercontent.com/8340592/97170984-9b844600-17c7-11eb-8c08-1e3c261b9728.png)

I expected `QPS` to appear for the bars, but `OPS` is used. Then I read the documentation but cannot find an explanation of the term.

**Describe the feature you'd like:**

Explain the abbreviations such as `OPS` on the dashboard

**Describe alternatives you've considered:**

Use the same term `QPS` consistently

**Teachability, Documentation, Adoption, Migration Strategy:**
https://docs.pingcap.com/zh/tidb/dev/dashboard-overview

**Comment by breeswish** [comment]
Thanks for the report! We are aware of this inconsistent. However it may require some notable effort to fix, which is related to the unit formatting library we use, since "ops" is a valid unit while "qps" is not. PRs are welcome!
