### ISSUE TITLE
UCP: Add TLS Support

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#87]
## Description

This task is to make TiDB Dashboard support TLS TiDB cluster. When Dashboard is running in standalone mode, TLS certificates of the TiDB cluster can be supplied by passing cli arguments. When Dashboard is running with PD, TLS certificates can be obtained from PD cli configuration.

You can see more descriptions in https://github.com/pingcap-incubator/tidb-dashboard/issues/174

## Score 

* 1680

Note: You can get 2530 in total if https://github.com/pingcap-incubator/tidb-dashboard/issues/177 is also implemented.

## Mentor(s)

* @breeswish 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Security
* Golang
* Web programming

**Comment by you06** [comment]
@niedhui this pick is success, but there are some accidents make the success comment failed.

**Comment by niedhui** [comment]
Got it. Working on #174 and #177
