### ISSUE TITLE
UCP: Support more metrics for statement API

### ISSUE THREAD

**Issue by baurine** [pingcap-incubator/tidb-dashboard#99]
## Description

This task is to support more metrics for statement API. 

(what metrics do we need? WIP)

## Score 

* 605

## Mentor(s)

* @baurine 
* @djshow832

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Go

**Comment by Kuri-su** [comment]
@baurine Maybe u know what metrics  your need now : )

**Comment by baurine** [comment]
hi @Kuri-su , we are implementing this issue by ourselves now, maybe you can try some other issues, sorry for it!

**Comment by Kuri-su** [comment]
> hi @Kuri-su , we are implementing this issue by ourselves now, maybe you can try some other issues, sorry for it!

:joy:

**Comment by breeswish** [comment]
Close since we are going to add nearly all available statement metrics to API in this week.
